Repository first-contributions-ja/first-contributions-ja.github.io, pull requests merged in 2024-06, with the labels that each got.

#206 Topページにコンセプトセクションを追加
  src/app/page.tsx
  src/components/ui/section-title.tsx
Labels: Type: 🎨 style

#207 吹き出しカードコンポーネントの実装
  next.config.js
  public/img-code.png
  src/app/globals.css
  src/app/layout.tsx
  src/app/page.tsx
  src/components/animated-emoji.tsx
  src/components/gradient-background.tsx
  src/components/ui/SpeechBubbleWrapper.tsx
  src/components/ui/speechBubbleItem.tsx
Labels: Type: 🎨 style

#209 Aboutセクションを追加
  public/img-code.png
  src/app/page.tsx
  src/components/ui/SpeechBubbleWrapper.tsx
  src/components/ui/button.tsx
  src/components/ui/section-title.tsx
Labels: Type: 🎨 style

#210 絵文字の表示の不具合を修正
  src/app/layout.tsx
  src/app/page.tsx
  src/components/animated-emoji.tsx
  src/components/hero-section-emoji-shower.tsx
Labels: Type: 🐛 fix

#213 タッチアイコン画像を角丸なしへ変更
  src/app/icon-192x192.png
  src/app/icon-512x512.png
Labels: Type: 🐛 fix

#214 apple-icon.png を角丸処理なしに変更
  src/app/apple-icon.png
Labels: Type: 🐛 fix

#220 ユーザーの傾向を考慮し、絵文字を逆順に表示する
  src/app/page.tsx
  src/components/animated-emoji.tsx
  src/components/screen-emojis.tsx
  src/utils/contributors-grouping.ts
  src/utils/contributors-reversed.ts
Labels: Type: 🐛 fix

#222 絵文字の表示順序変更に伴いREADME.md更新
  README.md
  docs/images/copy-and-paste-code.png
Labels: Type: 📚 docs
